spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://hyva.cqbwanh7lnnf.ap-northeast-2.rds.amazonaws.com:3306/hyva?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: Junction555
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true

openai:
  model: gpt-3.5-turbo
  api:
    organization: org-pD5CrdVGC331XKSlrYe3DUoK
    url: https://api.openai.com/v1/chat/completions
    key: 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

solum:
  api:
    url: https://stage00.common.solumesl.com/common/api

springdoc:
  packages-to-scan: com.example.api
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha

logging:
  level:
    org.springframework: DEBUG
