### 전체 유저 조회
GET http://localhost:8080/admin/all-user

### 전체 Tease 조회
GET http://localhost:8080/admin/all-tease

### 특정 유저의 전체 Tease 조회
GET http://localhost:8080/admin/user-all-tease?userId=1

### 특정 유저의 전체 Tease 삭제
DELETE http://localhost:8080/admin/user-all-tease?userId=1

### 특정 유저와 해당 유저의 전체 npc들의 상태 조회
GET http://localhost:8080/admin/user-npc-status?userId=1
